"use client";

import { withBase } from "@/lib/base";

type LogoVariant =
  | "auto"
  | "glass"
  | "light"
  | "dark"
  | "gold"
  | "white"
  | "black"
  | "mark"
  | "loading"
  | "vertical";

/**
 * Brand artwork — the Reddivaripalli village badge.
 *
 * The badge is one piece: scene, wordmark and motto ring together. There is no
 * separate emblem to show without the name, so every variant here is the same
 * artwork at a different size, and `variant` only chooses which file is light
 * enough for the context it renders in.
 *
 * Source: public/brand/reddivaripalli-logo-master.png
 *         → scripts/generate-logo-system.ts (npm run brand:logo)
 */
export function Logo({
  className = "",
  markOnly = false,
  variant = "auto",
  glossy = true,
  priority = false,
}: {
  className?: string;
  markOnly?: boolean;
  animated?: boolean;
  variant?: LogoVariant;
  /** Soft glass/gloss sheen. Default on for brand consistency. */
  glossy?: boolean;
  /** Mark the LCP logo candidate (home hero). */
  priority?: boolean;
}) {
  const vertical = variant === "vertical";
  const mark = markOnly || variant === "mark";

  // WebP delivery copies of the approved village lockup (public/logo/*.webp,
  // generated by scripts/generate-logo-system.ts from the master artwork).
  // The PNG masters stay on disk; they are 5–25x heavier and were the single
  // largest asset on the homepage.
  const src = withBase(
    mark
      ? "/logo/logo-mark.webp"
      : vertical
        ? "/logo/logo-vertical.webp"
        : "/logo/logo-master.webp",
  );

  return (
    <span
      className={[
        "brand-logo-shell",
        glossy ? "brand-logo-shell--gloss" : "",
        vertical ? "brand-logo-shell--vertical" : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <img
        className={`brand-logo ${vertical ? "brand-logo-vertical" : ""} ${className}`.trim()}
        src={src}
        alt="Reddivaripalli Village — Heritage, Community, Progress"
        // Intrinsic size of the file being loaded, so the browser reserves the
        // right box and the header does not jump as the badge decodes.
        width={mark ? 192 : vertical ? 640 : 320}
        height={mark ? 154 : vertical ? 513 : 256}
        draggable={false}
        decoding={priority ? "sync" : "async"}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : "low"}
      />
      {glossy ? (
        <span className="brand-logo-gloss-clip" aria-hidden>
          <span className="brand-logo-sheen" />
        </span>
      ) : null}
    </span>
  );
}
