/** Auto-generated by scripts/sync-community-seeds.ts — do not edit by hand */
export const COMMUNITY_SEEDS: Record<string, Record<string, unknown>[]> = {
  "members": [
    {
      "id": "g-ramesh-kumar-reddy",
      "name": "G Ramesh Kumar Reddy",
      "photo": "/members/g-ramesh-kumar-reddy.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Government Employee"
    },
    {
      "id": "g-hemanth-kumar-reddy",
      "name": "G Hemanth Kumar Reddy",
      "photo": "/members/hemanth.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Cyber Security Head (Software Engineer)"
    },
    {
      "id": "dr-g-uma-maheshwar-reddy",
      "name": "Dr. G Uma Maheshwar Reddy",
      "photo": "/members/g-uma.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Doctor (Orthopaedic MD)"
    },
    {
      "id": "g-dhanunjaya-reddy",
      "name": "G Dhanunjaya Reddy",
      "photo": "/members/dhanunjaya.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Government Employee – Vigilance Director"
    },
    {
      "id": "g-vijay-kumar-reddy",
      "name": "G Vijay Kumar Reddy",
      "photo": "/members/vijaykumar.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Business"
    },
    {
      "id": "g-rana-pathap-reddy",
      "name": "G Rana Prathap Reddy",
      "photo": "/members/rana.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Software Engineer"
    },
    {
      "id": "g-santhabushan-reddy",
      "name": "G Santhabushan Reddy",
      "photo": "/members/santhabushan.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Computer Science Engineer"
    },
    {
      "id": "d-harinatha",
      "name": "D Harinatha",
      "photo": "/members/d-harinatha.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Headmaster – Government School"
    },
    {
      "id": "g-raja",
      "name": "G Raja",
      "photo": "/members/g-raja.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Real Estate"
    },
    {
      "id": "y-naveen",
      "name": "Y Naveen",
      "photo": "/members/naveen.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Village Revenue Officer (VRO) – Government Employee"
    },
    {
      "id": "j-shiva",
      "name": "J Shiva",
      "photo": "/members/j-shiva.webp",
      "dob": null,
      "group": "legacy",
      "designation": "Government Teacher (Mathematics)"
    },
    {
      "id": "dr-u-reddy-prasad",
      "name": "Dr. U Reddy Prasad",
      "photo": null,
      "dob": null,
      "group": "legacy",
      "designation": "Doctor (Orthopaedic)"
    },
    {
      "id": "j-venkata-ramana-reddy",
      "name": "J Venkata Ramana Reddy",
      "photo": null,
      "dob": null,
      "group": "legacy",
      "designation": "Retired DSP – Government Service"
    },
    {
      "id": "d-manohar",
      "name": "D Manohar",
      "photo": null,
      "dob": null,
      "group": "legacy",
      "designation": "Government Employee – Managing Director, State Skill Development Corporation"
    },
    {
      "id": "g-govardhan-reddy",
      "name": "G Govardhan Reddy",
      "photo": "/members/govardhan.webp",
      "dob": "11-11",
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "g-pushyanth-reddy",
      "name": "G Pushyanth Reddy",
      "photo": null,
      "dob": "08-17",
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "c-narendra-cg",
      "name": "C Narendra (CG)",
      "photo": "/members/c-narendra-cg.webp",
      "dob": "10-10",
      "group": "core",
      "designation": "GRT Manager"
    },
    {
      "id": "m-rajesh",
      "name": "M Rajesh",
      "photo": "/members/rajesh.webp",
      "dob": "10-06",
      "group": "core",
      "designation": "Sales Manager"
    },
    {
      "id": "y-chenna-keshava",
      "name": "Y Chenna Keshava",
      "photo": "/members/keshava.webp",
      "dob": "06-15",
      "group": "core",
      "designation": "Business (Poultry)"
    },
    {
      "id": "g-sreekanth",
      "name": "G Sreekanth",
      "photo": "/members/sreekanth.webp",
      "dob": "06-04",
      "group": "core",
      "designation": "E-commerce Manager (Delivery)"
    },
    {
      "id": "c-narendra-ck",
      "name": "C Narendra (CK)",
      "photo": "/members/narendra-ck.webp",
      "dob": "02-17",
      "group": "core",
      "designation": "Mechanical Engineer"
    },
    {
      "id": "c-hari",
      "name": "C Hari",
      "photo": "/members/chari.webp",
      "dob": "08-15",
      "group": "core",
      "designation": "Bank Employee (Loan Department)"
    },
    {
      "id": "c-avinash",
      "name": "C Avinash",
      "photo": "/members/avinash.webp",
      "dob": "03-24",
      "group": "core",
      "designation": "Veterinary Professional"
    },
    {
      "id": "c-ganesh",
      "name": "C Ganesh",
      "photo": "/members/ganesh.webp",
      "dob": "01-02",
      "group": "core",
      "designation": "Electrical Engineer (UAE)"
    },
    {
      "id": "j-bhanu",
      "name": "J Bhanu",
      "photo": "/members/j-bhanu.webp",
      "dob": "10-08",
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "k-balaji",
      "name": "K Balaji",
      "photo": "/members/k-balaji.webp",
      "dob": "07-09",
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "y-krishna-mohan",
      "name": "Y Krishna Mohan",
      "photo": "/members/kittu.webp",
      "dob": null,
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "d-shantha-kumar",
      "name": "Dr. D Shantha Kumar",
      "photo": "/members/shantha.webp",
      "dob": "12-15",
      "group": "core",
      "designation": "Doctor (General Surgeon, MD)"
    },
    {
      "id": "u-nagendra",
      "name": "U Nagendra",
      "photo": "/members/nagendra.webp",
      "dob": "06-05",
      "group": "core",
      "designation": "Business"
    },
    {
      "id": "u-guru",
      "name": "U Guru",
      "photo": "/members/gurumahesh.webp",
      "dob": "09-02",
      "group": "core",
      "designation": "Software Engineer"
    },
    {
      "id": "u-guru-mahesh-puli",
      "name": "U Guru Mahesh (Puli)",
      "photo": "/members/guru.webp",
      "dob": "10-06",
      "group": "core",
      "designation": "GRT Employee"
    },
    {
      "id": "j-niranjan",
      "name": "J Niranjan Reddy",
      "photo": "/members/niranjan.webp",
      "dob": "09-11",
      "group": "core",
      "designation": "Indian Army"
    },
    {
      "id": "d-akhil-reddy",
      "name": "D Akhil Reddy",
      "photo": "/members/akhil.webp",
      "dob": "08-12",
      "group": "nextgen",
      "designation": "Software Engineer"
    },
    {
      "id": "d-anil-reddy",
      "name": "D Anil Reddy",
      "photo": "/members/laddu.webp",
      "dob": "05-22",
      "group": "nextgen",
      "designation": "Government Employee – Post Office"
    },
    {
      "id": "d-santhosh-reddy",
      "name": "D Santhosh Reddy",
      "photo": "/members/santhosh.webp",
      "dob": "08-16",
      "group": "nextgen",
      "designation": "Software Engineer"
    },
    {
      "id": "d-shiva-shankar-reddy",
      "name": "D Shiva Shankar Reddy",
      "photo": "/members/d-shiva.webp",
      "dob": "01-06",
      "group": "nextgen",
      "designation": "Agriculture Manager"
    },
    {
      "id": "u-nagesh",
      "name": "U Nagesh",
      "photo": "/members/u-nagesh.webp",
      "dob": "12-09",
      "group": "nextgen",
      "designation": "Software Engineer"
    },
    {
      "id": "c-ganu",
      "name": "C Ganu",
      "photo": "/members/ganu.webp",
      "dob": "06-15",
      "group": "nextgen",
      "designation": "Software Engineer"
    },
    {
      "id": "c-narasimha",
      "name": "C Narasimha",
      "photo": "/members/narasimha.webp",
      "dob": "11-12",
      "group": "nextgen",
      "designation": "Software Engineer"
    }
  ],
  "directory": [
    {
      "id": "dir-c-avinash",
      "name": "C Avinash",
      "category": "Doctors",
      "profession": "Veterinary",
      "designation": "Veterinary Professional",
      "photo": "/members/avinash.webp"
    },
    {
      "id": "dir-d-shantha-kumar",
      "name": "Dr. D Shantha Kumar",
      "category": "Doctors",
      "profession": "Doctor",
      "designation": "Doctor (General Surgeon, MD)",
      "photo": "/members/shantha.webp"
    },
    {
      "id": "dir-dr-g-uma-maheshwar-reddy",
      "name": "Dr. G Uma Maheshwar Reddy",
      "category": "Doctors",
      "profession": "Doctor",
      "designation": "Doctor (Orthopaedic MD)",
      "photo": "/members/g-uma.webp"
    },
    {
      "id": "dir-dr-u-reddy-prasad",
      "name": "Dr. U Reddy Prasad",
      "category": "Doctors",
      "profession": "Doctor",
      "designation": "Doctor (Orthopaedic)",
      "photo": null
    },
    {
      "id": "dir-d-harinatha",
      "name": "D Harinatha",
      "category": "Teachers",
      "profession": "Government Employee",
      "designation": "Headmaster – Government School",
      "photo": "/members/d-harinatha.webp"
    },
    {
      "id": "dir-j-shiva",
      "name": "J Shiva",
      "category": "Teachers",
      "profession": "Government Employee",
      "designation": "Government Teacher (Mathematics)",
      "photo": "/members/j-shiva.webp"
    },
    {
      "id": "dir-c-hari",
      "name": "C Hari",
      "category": "Other Professionals",
      "profession": "Banking",
      "designation": "Bank Employee (Loan Department)",
      "photo": "/members/chari.webp"
    },
    {
      "id": "dir-d-anil-reddy",
      "name": "D Anil Reddy",
      "category": "Government Employees",
      "profession": "Government Employee",
      "designation": "Government Employee – Post Office",
      "photo": "/members/laddu.webp"
    },
    {
      "id": "dir-g-dhanunjaya-reddy",
      "name": "G Dhanunjaya Reddy",
      "category": "Government Employees",
      "profession": "Government Employee",
      "designation": "Government Employee – Vigilance Director",
      "photo": "/members/dhanunjaya.webp"
    },
    {
      "id": "dir-g-ramesh-kumar-reddy",
      "name": "G Ramesh Kumar Reddy",
      "category": "Government Employees",
      "profession": "Government Employee",
      "designation": "Government Employee",
      "photo": "/members/g-ramesh-kumar-reddy.webp"
    },
    {
      "id": "dir-j-niranjan",
      "name": "J Niranjan Reddy",
      "category": "Government Employees",
      "profession": "Defence",
      "designation": "Indian Army",
      "photo": "/members/niranjan.webp"
    },
    {
      "id": "dir-y-naveen",
      "name": "Y Naveen",
      "category": "Government Employees",
      "profession": "Government Employee",
      "designation": "Village Revenue Officer (VRO) – Government Employee",
      "photo": "/members/naveen.webp"
    },
    {
      "id": "dir-c-ganesh",
      "name": "C Ganesh",
      "category": "Other Professionals",
      "profession": "Engineer",
      "designation": "Electrical Engineer (UAE)",
      "photo": "/members/ganesh.webp"
    },
    {
      "id": "dir-c-ganu",
      "name": "C Ganu",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/ganu.webp"
    },
    {
      "id": "dir-c-narasimha",
      "name": "C Narasimha",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/narasimha.webp"
    },
    {
      "id": "dir-c-narendra-cg",
      "name": "C Narendra (CG)",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "GRT Manager",
      "photo": "/members/c-narendra-cg.webp"
    },
    {
      "id": "dir-c-narendra-ck",
      "name": "C Narendra (CK)",
      "category": "Other Professionals",
      "profession": "Engineer",
      "designation": "Mechanical Engineer",
      "photo": "/members/narendra-ck.webp"
    },
    {
      "id": "dir-d-akhil-reddy",
      "name": "D Akhil Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/akhil.webp"
    },
    {
      "id": "dir-d-santhosh-reddy",
      "name": "D Santhosh Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/santhosh.webp"
    },
    {
      "id": "dir-d-shiva-shankar-reddy",
      "name": "D Shiva Shankar Reddy",
      "category": "Other Professionals",
      "profession": "Agriculture",
      "designation": "Agriculture Manager",
      "photo": "/members/d-shiva.webp"
    },
    {
      "id": "dir-g-govardhan-reddy",
      "name": "G Govardhan Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/govardhan.webp"
    },
    {
      "id": "dir-g-hemanth-kumar-reddy",
      "name": "G Hemanth Kumar Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Cyber Security Head (Software Engineer)",
      "photo": "/members/hemanth.webp"
    },
    {
      "id": "dir-g-pushyanth-reddy",
      "name": "G Pushyanth Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": null
    },
    {
      "id": "dir-g-raja",
      "name": "G Raja",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "Real Estate",
      "photo": "/members/g-raja.webp"
    },
    {
      "id": "dir-g-rana-pathap-reddy",
      "name": "G Rana Prathap Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/rana.webp"
    },
    {
      "id": "dir-g-sreekanth",
      "name": "G Sreekanth",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "E-commerce Manager (Delivery)",
      "photo": "/members/sreekanth.webp"
    },
    {
      "id": "dir-g-vijay-kumar-reddy",
      "name": "G Vijay Kumar Reddy",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "Business",
      "photo": "/members/vijaykumar.webp"
    },
    {
      "id": "dir-j-bhanu",
      "name": "J Bhanu",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/j-bhanu.webp"
    },
    {
      "id": "dir-k-balaji",
      "name": "K Balaji",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/k-balaji.webp"
    },
    {
      "id": "dir-m-rajesh",
      "name": "M Rajesh",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "Sales Manager",
      "photo": "/members/rajesh.webp"
    },
    {
      "id": "dir-u-guru",
      "name": "U Guru",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/gurumahesh.webp"
    },
    {
      "id": "dir-u-guru-mahesh-puli",
      "name": "U Guru Mahesh (Puli)",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "GRT Employee",
      "photo": "/members/guru.webp"
    },
    {
      "id": "dir-u-nagendra",
      "name": "U Nagendra",
      "category": "Other Professionals",
      "profession": "Business",
      "designation": "Business",
      "photo": "/members/nagendra.webp"
    },
    {
      "id": "dir-u-nagesh",
      "name": "U Nagesh",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/u-nagesh.webp"
    },
    {
      "id": "dir-y-chenna-keshava",
      "name": "Y Chenna Keshava",
      "category": "Other Professionals",
      "profession": "Agriculture",
      "designation": "Business (Poultry)",
      "photo": "/members/keshava.webp"
    },
    {
      "id": "dir-y-krishna-mohan",
      "name": "Y Krishna Mohan",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Software Engineer",
      "photo": "/members/kittu.webp"
    },
    {
      "id": "dir-g-santhabushan-reddy",
      "name": "G Santhabushan Reddy",
      "category": "Other Professionals",
      "profession": "Software / IT",
      "designation": "Computer Science Engineer",
      "photo": "/members/santhabushan.webp"
    }
  ],
  "events": [
    {
      "id": "ugadi-2026",
      "title": "Ugadi",
      "date": "2026-03-19",
      "image": "/festivals/ugadi/hero.webp",
      "description": "Telugu New Year — kalash, mango leaves, and a fresh beginning for the village.",
      "category": "festival",
      "slug": "ugadi",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "ఉగాది"
    },
    {
      "id": "sri-rama-navami-2026",
      "title": "Sri Rama Navami",
      "date": "2026-03-27",
      "image": "/festivals/sri-rama-navami/hero.webp",
      "description": "Hymns and flowers at Ramalayam — a day of grace in Kondreddigaripalli.",
      "category": "festival",
      "slug": "sri-rama-navami",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "శ్రీ రామ నవమి"
    },
    {
      "id": "mathamma-jathara-2026",
      "title": "Mathamma Jathara",
      "date": "2026-05-01",
      "image": "/festivals/mathamma-jathara/hero.webp",
      "description": "The village gathers for Mathamma — drums, offerings, and shared faith.",
      "category": "festival",
      "slug": "mathamma-jathara",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "మాతమ్మ జాతర"
    },
    {
      "id": "devapatlamma-jathara-2026",
      "title": "Devapatlamma Jathara",
      "date": "2026-06-01",
      "image": "/festivals/devapatlamma-jathara/hero.webp",
      "description": "Devapatlamma’s festival — temple light, community, and ancestral blessing.",
      "category": "festival",
      "slug": "devapatlamma-jathara",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "దేవపట్లమ్మ జాతర"
    },
    {
      "id": "varalakshmi-vratam-2026",
      "title": "Varalakshmi Vratam",
      "date": "2026-08-28",
      "image": "/festivals/varalakshmi-vratam/hero.webp",
      "description": "A sacred vow for Goddess Lakshmi — lamps, flowers, and family devotion.",
      "category": "festival",
      "slug": "varalakshmi-vratam",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "వరలక్ష్మీ వ్రతం"
    },
    {
      "id": "vinayaka-chavithi-2026",
      "title": "Vinayaka Chavithi",
      "date": "2026-09-14",
      "image": "/festivals/vinayaka-chavithi/hero.webp",
      "description": "Clay idols, lamp glow, and first prayers — a beloved beginning each monsoon season.",
      "category": "festival",
      "slug": "vinayaka-chavithi",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "వినాయక చవితి"
    },
    {
      "id": "dasara-2026",
      "title": "Dasara",
      "date": "2026-10-20",
      "image": "/festivals/dasara/hero.webp",
      "description": "Nine nights of devotion culminating in village celebration and colour.",
      "category": "festival",
      "slug": "dasara",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "దసరా"
    },
    {
      "id": "deepavali-2026",
      "title": "Deepavali",
      "date": "2026-11-08",
      "image": "/festivals/deepavali/hero.webp",
      "description": "Rows of diyas, rangoli glow, and the festival of lights across every home.",
      "category": "festival",
      "slug": "deepavali",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "దీపావళి"
    },
    {
      "id": "sankranthi-2027",
      "title": "Sankranti",
      "date": "2027-01-14",
      "endDate": "2027-01-15",
      "image": "/festivals/sankranti/hero.webp",
      "description": "Harvest light, rangoli, and the village gathering to begin the year together.",
      "category": "festival",
      "slug": "sankranthi",
      "reminderDaysBefore": 7,
      "recurring": true,
      "titleTe": "సంక్రాంతి"
    }
  ],
  "announcements": [
    {
      "id": "welcome-2026",
      "title": "Welcome to the Reddivaripalli digital home",
      "body": "Browse festivals, members, birthdays, developments, and village memories. Stewards: RVP Youth.",
      "date": "2026-01-01",
      "important": false
    },
    {
      "id": "contact-inbox-2026",
      "title": "Community inbox is open",
      "body": "Have a suggestion or need to reach the community?",
      "date": "2026-08-04",
      "important": true,
      "href": "/contact/",
      "cta": "Contact Us",
      "titleTe": "మీ సందేశాలకు స్వాగతం",
      "bodyTe": "సూచన ఉందా? లేదా గ్రామ సమాజాన్ని సంప్రదించాలా?",
      "ctaTe": "మమ్మల్ని సంప్రదించండి"
    },
    {
      "id": "ramalayam-dev-2026",
      "title": "Sri Ramalayam development updates",
      "body": "Follow planning and progress on the Developments page. Suggestions from villagers are welcome under Suggestions.",
      "date": "2026-08-01",
      "important": false
    }
  ],
  "families": [
    {
      "id": "GUNDLURU_KONDA_REDDY",
      "name": "Gundluru Konda Reddy Family",
      "slug": "gundluru-konda-reddy",
      "description": "A family branch of Reddivaripalli. This is a separate family from the Gundluru Venkata Subba Reddy Family.",
      "displayOrder": 1,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "GUNDLURU_VENKATA_SUBBA_REDDY",
      "name": "Gundluru Venkata Subba Reddy Family",
      "slug": "gundluru-venkata-subba-reddy",
      "description": "A family branch of Reddivaripalli. This is a separate family from the Gundluru Konda Reddy Family.",
      "displayOrder": 2,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "KUNCHAPU",
      "name": "Kunchapu Family",
      "slug": "kunchapu",
      "description": "The Kunchapu family of Reddivaripalli.",
      "displayOrder": 3,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "MARIMENI",
      "name": "Marimeni Family",
      "slug": "marimeni",
      "description": "The Marimeni family of Reddivaripalli. This is a separate family from the Marimeni Nadupanna Family.",
      "displayOrder": 4,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "DEVAPATLA",
      "name": "Devapatla Family",
      "slug": "devapatla",
      "description": "The Devapatla family of Reddivaripalli.",
      "displayOrder": 5,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "MARIMENI_NADUPANNA",
      "name": "Marimeni Nadupanna Family",
      "slug": "marimeni-nadupanna",
      "description": "The Marimeni Nadupanna family of Reddivaripalli. This is a separate family from the Marimeni Family.",
      "displayOrder": 6,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "KOMMEPALLI",
      "name": "Kommepalli Family",
      "slug": "kommepalli",
      "description": "The Kommepalli family of Reddivaripalli. People can be assigned to this branch by an administrator.",
      "displayOrder": 7,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "KUDUM",
      "name": "Kudum Family",
      "slug": "kudum",
      "description": "The Kudum family of Reddivaripalli. People can be assigned to this branch by an administrator.",
      "displayOrder": 8,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "JAGADAM",
      "name": "Jagadam Family",
      "slug": "jagadam",
      "description": "The Jagadam family of Reddivaripalli. This is a separate family from the Jagili Family.",
      "displayOrder": 9,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "JAGILI",
      "name": "Jagili Family",
      "slug": "jagili",
      "description": "The Jagili family of Reddivaripalli. This is a separate family from the Jagadam Family. People can be assigned to this branch by an administrator.",
      "displayOrder": 10,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "USIRIKAYALA",
      "name": "Usirikayala Family",
      "slug": "usirikayala",
      "description": "The Usirikayala family of Reddivaripalli.",
      "displayOrder": 11,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "CHINTHAMANI",
      "name": "Chinthamani Family",
      "slug": "chinthamani",
      "description": "The Chinthamani family of Reddivaripalli.",
      "displayOrder": 12,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    },
    {
      "id": "YERRAGOLLA",
      "name": "Yerragolla Family",
      "slug": "yerragolla",
      "description": "The Yerragolla family of Reddivaripalli.",
      "displayOrder": 13,
      "coverPhoto": null,
      "history": "Information not yet provided.",
      "isPublished": true,
      "createdAt": "2026-09-04T00:00:00.000Z",
      "updatedAt": "2026-09-04T00:00:00.000Z"
    }
  ],
  "family-people": [],
  "media-protection": []
} as Record<string, Record<string, unknown>[]>;
