/**
 * Generate PBKDF2 password hashes for Fun Fest member login.
 *
 * DEPRECATED for credential rotation — use scripts/rotate-member-passwords.ts,
 * which writes plaintext outside the repository and never to git.
 *
 * This script keeps existing records intact so `prepare:site` stays idempotent.
 * For a member with no existing record it now mints a RANDOM password and
 * writes it to $HOME/rvp-credentials/NEW-MEMBERS-<stamp>.csv rather than
 * setting the password to the username. Deriving a password from a public
 * username is what caused docs/SECURITY_INCIDENT.md finding S-1.
 *
 * Writes:
 *  - functions/_data/member-auth.json  (reference / backups)
 *  - functions/_data/member-auth-data.ts (imported by Pages Functions)
 *
 *   npm run auth:members
 *   npm run auth:members:force
 */
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { assignMemberUsernames } from "../lib/auth";
import type { Member } from "../lib/types";

const ROOT = process.cwd();
const MEMBERS_PATH = path.join(ROOT, "content", "data", "members.json");
const OUT_JSON = path.join(ROOT, "functions", "_data", "member-auth.json");
const OUT_TS = path.join(ROOT, "functions", "_data", "member-auth-data.ts");
const FORCE = process.env.MEMBER_AUTH_FORCE === "1";

type AuthRecord = {
  memberId: string;
  username: string;
  name: string;
  passwordHash: string;
  updatedAt: string;
};

const ALPHABET = "abcdefghijkmnpqrstuvwxyzACDEFGHJKLMNPQRSTUVWXYZ23456789";

/** Random, unambiguous temporary password for a member with no record yet. */
function generatePassword(length = 14): string {
  const bytes = crypto.randomBytes(length * 2);
  let out = "";
  for (let i = 0; out.length < length && i < bytes.length; i += 1) {
    const b = bytes[i]!;
    if (b >= 256 - (256 % ALPHABET.length)) continue;
    out += ALPHABET[b % ALPHABET.length];
  }
  return out.length === length ? out : generatePassword(length);
}

function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16).toString("hex");
  // 100k fits Cloudflare Workers CPU limits while remaining salted/slow.
  const hash = crypto
    .pbkdf2Sync(password, salt, 100_000, 32, "sha256")
    .toString("base64url");
  return `pbkdf2:${salt}:${hash}`;
}

function main() {
  if (!fs.existsSync(MEMBERS_PATH)) {
    console.error(`Members seed missing: ${path.relative(ROOT, MEMBERS_PATH)}`);
    process.exit(1);
  }
  console.log(
    `Fun Fest auth ← ${path.relative(ROOT, MEMBERS_PATH)} (single source of truth)`,
  );
  const members = JSON.parse(fs.readFileSync(MEMBERS_PATH, "utf8")) as Member[];
  const usernames = assignMemberUsernames(members);
  const existing = (
    !FORCE && fs.existsSync(OUT_JSON)
      ? (JSON.parse(fs.readFileSync(OUT_JSON, "utf8")) as {
          members: AuthRecord[];
        })
      : { members: [] }
  ).members;
  const byId = new Map(existing.map((r) => [r.memberId, r]));
  const next: AuthRecord[] = [];
  const minted: string[][] = [];

  for (const member of members) {
    const username = usernames.get(member.id);
    if (!username) continue;
    const prev = byId.get(member.id);
    if (prev && prev.username === username && !FORCE) {
      next.push({ ...prev, name: member.name, username });
      continue;
    }
    const tempPassword = generatePassword();
    next.push({
      memberId: member.id,
      username,
      name: member.name,
      passwordHash: hashPassword(tempPassword),
      updatedAt: new Date().toISOString(),
    });
    minted.push([username, member.name, tempPassword]);
    // Never log the password.
    console.log(`Minted temporary credential for ${username} ← ${member.name}`);
  }

  const payload = {
    version: 1,
    note: "Fun Fest credentials — PBKDF2 hashes only. Update passwordHash to change a password without code changes.",
    members: next,
    generatedAt: new Date().toISOString(),
  };

  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, JSON.stringify(payload, null, 2));
  fs.writeFileSync(
    OUT_TS,
    `/* Auto-generated by scripts/generate-member-auth.ts — do not edit by hand */\n` +
      `export type MemberAuthRecord = {\n` +
      `  memberId: string;\n` +
      `  username: string;\n` +
      `  name: string;\n` +
      `  passwordHash: string;\n` +
      `  updatedAt: string;\n` +
      `};\n\n` +
      `export const MEMBER_AUTH: { version: number; members: MemberAuthRecord[] } = ${JSON.stringify(
        { version: 1, members: next },
        null,
        2,
      )} as const;\n`,
  );
  if (minted.length) {
    const dir = path.join(os.homedir(), "rvp-credentials");
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const file = path.join(dir, `NEW-MEMBERS-${stamp}.csv`);
    fs.writeFileSync(
      file,
      ["username,name,temporary_password"]
        .concat(minted.map((r) => r.join(",")))
        .join("\n") + "\n",
      { mode: 0o600 },
    );
    console.log("");
    console.log(`${minted.length} new member(s) got a random temporary password.`);
    console.log(`  ${file}   (SENSITIVE — deliver individually, then delete)`);
  }
  console.log(`Wrote ${next.length} auth records → ${path.relative(ROOT, OUT_JSON)}`);
  console.log(`Wrote Functions module → ${path.relative(ROOT, OUT_TS)}`);
}

main();
