import fs from "node:fs";
import path from "node:path";
import { publicAlbums, allMedia, years } from "../lib/content";
import { BUCKETS, albumHref } from "../lib/site";

const root = process.cwd();
const url =
  process.env.NEXT_PUBLIC_SITE_URL || "https://www.reddivaripalli.com";
const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
const albums = publicAlbums();
const media = allMedia();

const live = albums.filter((a) => (a.media?.length ?? 0) > 0);
const bucketsWithContent = BUCKETS.filter((b) =>
  live.some((a) => a.bucket === b.key),
);
const routes = [
  "",
  "search",
  "about",
  "years",
  "members",
  "events",
  "gallery",
  // Only buckets that have uploaded media — empty CMS folders stay hidden
  ...bucketsWithContent.map((b) => b.key),
  ...years().map((year) => `years/${year}`),
  ...bucketsWithContent.flatMap((b) => {
    const ys = [
      ...new Set(live.filter((a) => a.bucket === b.key).map((a) => a.year)),
    ];
    return ys.map((year) => `${b.key}/${year}`);
  }),
  ...live.map((album) => albumHref(album).replace(/^\/|\/$/g, "")),
];

fs.writeFileSync(
  path.join(root, "public", "search-index.json"),
  JSON.stringify(
    media.map((item) => ({
      title: item.title,
      date: item.date,
      tags: item.tags,
      type: item.type,
      album: item.album.title,
      bucket: item.album.bucket,
      year: item.album.year,
      url: `${base}${albumHref(item.album)}`,
    })),
    null,
    2,
  ),
);

fs.writeFileSync(
  path.join(root, "public", "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[
    ...new Set(routes),
  ]
    .map((route) => `<url><loc>${url}/${route}</loc></url>`)
    .join("")}</urlset>`,
);

fs.writeFileSync(
  path.join(root, "public", "feed.xml"),
  `<?xml version="1.0"?><rss version="2.0"><channel><title>RVP Youth</title><link>${url}</link><description>Premium memory experience</description>${albums
    .map(
      (album) =>
        `<item><title>${album.title}</title><link>${url}${albumHref(album)}</link><description>${album.description}</description></item>`,
    )
    .join("")}</channel></rss>`,
);

const buildId =
  process.env.CF_PAGES_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  process.env.VERCEL_GIT_COMMIT_SHA ||
  Date.now().toString(36);

// Apps poll this file — every deploy gets a new id so data/images refresh
fs.writeFileSync(
  path.join(root, "public", "version.json"),
  JSON.stringify(
    {
      buildId,
      builtAt: new Date().toISOString(),
      site: url,
    },
    null,
    2,
  ),
);

// Cache-bust media URLs in the client after every deploy
fs.writeFileSync(
  path.join(root, "lib", "build-id.ts"),
  `/** Auto-generated by scripts/generate-all.ts — do not edit */\nexport const BUILD_ID = ${JSON.stringify(buildId)};\n`,
);

fs.writeFileSync(
  path.join(root, "public", "sw.js"),
  `const CACHE=${JSON.stringify(`rvp-youth-${buildId}`)},BUILD=${JSON.stringify(buildId)},BASE=${JSON.stringify(base || "")};
self.addEventListener("message",e=>{if(e.data&&e.data.type==="SKIP_WAITING")self.skipWaiting()});
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll([BASE+"/",BASE+"/offline/",BASE+"/version.json"]).catch(()=>{})));self.skipWaiting()});
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{
  if(e.request.method!=="GET")return;
  const req=e.request;
  const url=new URL(req.url);
  if(url.origin!==self.location.origin)return;
  // Always hit network for deploy version + SW itself
  if(url.pathname.endsWith("/version.json")||url.pathname.endsWith("/sw.js")||url.pathname.endsWith("/manifest.webmanifest")){
    e.respondWith(fetch(new Request(req,{cache:"no-store"})).catch(()=>caches.match(req)));
    return;
  }
  const isNav=req.mode==="navigate";
  // Network-first for pages + media so every deploy shows new data/images online
  if(isNav||/\\.(?:png|jpe?g|webp|avif|gif|svg|json|html?)(?:\\?|$)/i.test(url.pathname)||url.pathname.includes("/media/")||url.pathname.includes("/thumbs/")||url.pathname.includes("/brand/")||url.pathname.includes("/logo/")||url.pathname.includes("/content/")){
    e.respondWith(fetch(req).then(r=>{if(r&&r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(req,copy));}return r}).catch(()=>caches.match(req).then(r=>r||(isNav?caches.match(BASE+"/offline/").then(o=>o||caches.match(BASE+"/")):undefined))));
    return;
  }
  e.respondWith(fetch(req).then(r=>{if(r&&r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(req,copy));}return r}).catch(()=>caches.match(req)));
});
`,
);

fs.writeFileSync(
  path.join(root, "public", "robots.txt"),
  `User-agent: *\nAllow: /\nSitemap: ${url}/sitemap.xml\n`,
);

const startUrl = base ? `${base}/` : "/";
const iconBase = base || "";
fs.writeFileSync(
  path.join(root, "public", "manifest.webmanifest"),
  JSON.stringify(
    {
      id: startUrl,
      name: "RVP Youth",
      short_name: "RVP Youth",
      description:
        "Where Every Celebration Becomes a Legacy. Our Village. Our Heritage. Our Memories.",
      start_url: startUrl,
      scope: base || "/",
      display: "standalone",
      display_override: ["standalone", "fullscreen", "browser"],
      orientation: "any",
      lang: "en",
      dir: "ltr",
      categories: ["lifestyle", "photo", "entertainment"],
      background_color: "#0f1a14",
      theme_color: "#1f3d2e",
      prefer_related_applications: false,
      icons: [
        {
          src: `${iconBase}/logo/android-icon.png`,
          sizes: "192x192",
          type: "image/png",
          purpose: "any",
        },
        {
          src: `${iconBase}/logo/android-icon.png`,
          sizes: "192x192",
          type: "image/png",
          purpose: "maskable",
        },
        {
          src: `${iconBase}/logo/app-icon.png`,
          sizes: "512x512",
          type: "image/png",
          purpose: "any",
        },
        {
          src: `${iconBase}/logo/app-icon.png`,
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable",
        },
        {
          src: `${iconBase}/logo/apple-touch-icon.png`,
          sizes: "180x180",
          type: "image/png",
          purpose: "any",
        },
      ],
      shortcuts: [
        {
          name: "Sankranthi",
          short_name: "Sankranthi",
          url: `${base}/sankranthi/`,
          icons: [
            {
              src: `${iconBase}/logo/android-icon.png`,
              sizes: "192x192",
            },
          ],
        },
        {
          name: "Vinayaka Chavithi",
          short_name: "Vinayaka",
          url: `${base}/vinayaka-chavithi/`,
          icons: [
            {
              src: `${iconBase}/logo/android-icon.png`,
              sizes: "192x192",
            },
          ],
        },
      ],
    },
    null,
    2,
  ),
);

console.log(`Generated SEO assets for ${albums.length} RVP Youth albums.`);
