/**
 * Generate PBKDF2 password hashes for Fun Fest member login.
 * Initial password = case-sensitive username.
 *
 * Writes:
 *  - functions/_data/member-auth.json  (reference / backups)
 *  - functions/_data/member-auth-data.ts (imported by Pages Functions)
 *
 *   npm run auth:members
 *   npm run auth:members:force
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { assignMemberUsernames } from "../lib/auth";
import type { Member } from "../lib/types";

const ROOT = process.cwd();
const MEMBERS_PATH = path.join(ROOT, "content", "data", "members.json");
const OUT_JSON = path.join(ROOT, "functions", "_data", "member-auth.json");
const OUT_TS = path.join(ROOT, "functions", "_data", "member-auth-data.ts");
const FORCE = process.env.MEMBER_AUTH_FORCE === "1";

type AuthRecord = {
  memberId: string;
  username: string;
  name: string;
  passwordHash: string;
  updatedAt: string;
};

function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16).toString("hex");
  // 100k fits Cloudflare Workers CPU limits while remaining salted/slow.
  const hash = crypto
    .pbkdf2Sync(password, salt, 100_000, 32, "sha256")
    .toString("base64url");
  return `pbkdf2:${salt}:${hash}`;
}

function main() {
  const members = JSON.parse(fs.readFileSync(MEMBERS_PATH, "utf8")) as Member[];
  const usernames = assignMemberUsernames(members);
  const existing = (
    !FORCE && fs.existsSync(OUT_JSON)
      ? (JSON.parse(fs.readFileSync(OUT_JSON, "utf8")) as {
          members: AuthRecord[];
        })
      : { members: [] }
  ).members;
  const byId = new Map(existing.map((r) => [r.memberId, r]));
  const next: AuthRecord[] = [];

  for (const member of members) {
    const username = usernames.get(member.id);
    if (!username) continue;
    const prev = byId.get(member.id);
    if (prev && prev.username === username && !FORCE) {
      next.push({ ...prev, name: member.name, username });
      continue;
    }
    next.push({
      memberId: member.id,
      username,
      name: member.name,
      passwordHash: hashPassword(username),
      updatedAt: new Date().toISOString(),
    });
    console.log(`Hashed ${username} ← ${member.name}`);
  }

  const payload = {
    version: 1,
    note: "Fun Fest credentials — PBKDF2 hashes only. Update passwordHash to change a password without code changes.",
    members: next,
    generatedAt: new Date().toISOString(),
  };

  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, JSON.stringify(payload, null, 2));
  fs.writeFileSync(
    OUT_TS,
    `/* Auto-generated by scripts/generate-member-auth.ts — do not edit by hand */\n` +
      `export type MemberAuthRecord = {\n` +
      `  memberId: string;\n` +
      `  username: string;\n` +
      `  name: string;\n` +
      `  passwordHash: string;\n` +
      `  updatedAt: string;\n` +
      `};\n\n` +
      `export const MEMBER_AUTH: { version: number; members: MemberAuthRecord[] } = ${JSON.stringify(
        { version: 1, members: next },
        null,
        2,
      )} as const;\n`,
  );
  console.log(`Wrote ${next.length} auth records → ${path.relative(ROOT, OUT_JSON)}`);
  console.log(`Wrote Functions module → ${path.relative(ROOT, OUT_TS)}`);
}

main();
