/**
 * Sync content/data/*.json into functions/_data/community-seeds.ts
 * so the community API can serve Git seed when R2 is unseeded.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const COLLECTIONS = ["members", "directory", "events", "announcements"] as const;

const out: Record<string, unknown[]> = {};
for (const name of COLLECTIONS) {
  const raw = readFileSync(join(ROOT, `content/data/${name}.json`), "utf8");
  out[name] = JSON.parse(raw) as unknown[];
}

const body =
  "/** Auto-generated by scripts/sync-community-seeds.ts — do not edit by hand */\n" +
  "export const COMMUNITY_SEEDS: Record<string, Record<string, unknown>[]> = " +
  JSON.stringify(out, null, 2) +
  " as Record<string, Record<string, unknown>[]>;\n";

writeFileSync(join(ROOT, "functions/_data/community-seeds.ts"), body);
console.log(
  "Synced community seeds:",
  Object.fromEntries(Object.entries(out).map(([k, v]) => [k, v.length])),
);
