/**
 * Central government services and the national aggregators.
 *
 * The aggregators come first on purpose: india.gov.in, services.india.gov.in,
 * UMANG and DigiLocker already index thousands of services between them, and
 * duplicating that here would guarantee a stale copy. What this file adds is
 * the two dozen destinations a villager in Reddivaripalli actually needs by
 * name, so they do not have to know which aggregator to start from.
 */
import { entry, type DirectoryEntry } from "./types";

const V = "2026-08-28";
const NP = {
  source: "National Portal of India",
  sourceUrl: "https://www.india.gov.in/",
  lastVerified: V,
};

export const CENTRAL: DirectoryEntry[] = [
  entry({
    id: "india-gov",
    name: "India.gov.in — National Portal",
    nameTe: "భారత జాతీయ పోర్టల్",
    description: "The government's own index of central and state services.",
    descriptionTe: "కేంద్ర, రాష్ట్ర సేవలన్నింటికీ ప్రభుత్వ అధికారిక సూచిక.",
    category: "aggregator",
    audience: ["everyone"],
    level: "central",
    department: "Government of India",
    officialUrl: "https://www.india.gov.in/",
    keywords: ["india", "portal", "government", "services", "సేవలు"],
    ...NP,
  }),
  entry({
    id: "services-india",
    name: "Government Services Portal",
    nameTe: "ప్రభుత్వ సేవల పోర్టల్",
    description:
      "Searchable directory of every service the government publishes, filterable by state.",
    descriptionTe: "రాష్ట్రం వారీగా వెతకగల ప్రభుత్వ సేవల డైరెక్టరీ.",
    category: "aggregator",
    audience: ["everyone"],
    level: "central",
    department: "Government of India",
    officialUrl: "https://services.india.gov.in/",
    keywords: ["services", "directory", "search", "సేవలు"],
    ...NP,
  }),
  entry({
    id: "umang",
    name: "UMANG",
    nameTe: "ఉమంగ్",
    description:
      "One app and website for hundreds of central and state services, including EPFO and gas.",
    descriptionTe: "వందలాది కేంద్ర, రాష్ట్ర సేవలు ఒకే యాప్‌లో.",
    category: "aggregator",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Electronics & IT",
    officialUrl: "https://www.umang.gov.in/",
    keywords: ["umang", "app", "ఉమంగ్"],
    ...NP,
  }),
  entry({
    id: "digilocker",
    name: "DigiLocker",
    nameTe: "డిజిలాకర్",
    description:
      "Your official documents in digital form — marksheets, driving licence, RC, PAN, Aadhaar and more, issued directly by the authority.",
    descriptionTe:
      "మార్కుల మెమో, డ్రైవింగ్ లైసెన్స్, ఆర్‌సి, పాన్, ఆధార్ వంటి అధికారిక పత్రాలు డిజిటల్ రూపంలో.",
    category: "identity",
    audience: ["everyone", "students"],
    level: "central",
    department: "Ministry of Electronics & IT",
    officialUrl: "https://www.digilocker.gov.in/",
    keywords: [
      "digilocker", "documents", "marksheet", "marks memo", "certificate",
      "డిజిలాకర్", "పత్రాలు", "మార్కుల మెమో",
    ],
    ...NP,
  }),
  entry({
    id: "uidai",
    name: "Aadhaar (UIDAI)",
    nameTe: "ఆధార్",
    description: "Enrolment, update, download and Aadhaar status.",
    descriptionTe: "ఆధార్ నమోదు, మార్పులు, డౌన్‌లోడ్ మరియు స్థితి.",
    category: "identity",
    audience: ["everyone"],
    level: "central",
    department: "Unique Identification Authority of India",
    officialUrl: "https://uidai.gov.in/",
    keywords: ["aadhaar", "aadhar", "adhar", "uid", "ఆధార్"],
    ...NP,
  }),
  entry({
    id: "incometax",
    name: "Income Tax — PAN and returns",
    nameTe: "ఆదాయపు పన్ను — పాన్",
    description: "Apply for PAN, correct it, link Aadhaar and file returns.",
    descriptionTe: "పాన్ కోసం దరఖాస్తు, సవరణ, ఆధార్ లింక్, రిటర్న్‌లు.",
    category: "money",
    audience: ["everyone", "business"],
    level: "central",
    department: "Income Tax Department",
    officialUrl: "https://www.incometax.gov.in/",
    keywords: ["pan", "income tax", "itr", "e-pan", "పాన్", "ఆదాయపు పన్ను"],
    ...NP,
  }),
  entry({
    id: "voters",
    name: "Voter services",
    nameTe: "ఓటరు సేవలు",
    description: "Voter ID, new registration, corrections and roll search.",
    descriptionTe: "ఓటరు కార్డు, కొత్త నమోదు, సవరణలు, జాబితా వెతకడం.",
    category: "identity",
    audience: ["everyone"],
    level: "central",
    department: "Election Commission of India",
    officialUrl: "https://voters.eci.gov.in/",
    keywords: ["voter", "voter id", "epic", "election", "ఓటరు"],
    ...NP,
  }),
  entry({
    id: "passport",
    name: "Passport Seva",
    nameTe: "పాస్‌పోర్ట్ సేవ",
    description: "Passport application, appointment and status.",
    descriptionTe: "పాస్‌పోర్ట్ దరఖాస్తు, అపాయింట్‌మెంట్, స్థితి.",
    category: "travel",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of External Affairs",
    officialUrl: "https://www.passportindia.gov.in/",
    keywords: ["passport", "పాస్‌పోర్ట్"],
    ...NP,
  }),
  entry({
    id: "parivahan",
    name: "Parivahan — licence and vehicle",
    nameTe: "పరివాహన్ — లైసెన్స్, వాహనం",
    description:
      "Learner and driving licence, vehicle registration, RC, road tax and challans.",
    descriptionTe:
      "లెర్నర్, డ్రైవింగ్ లైసెన్స్, వాహన నమోదు, ఆర్‌సి, రోడ్డు పన్ను, చలానాలు.",
    category: "transport",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Road Transport & Highways",
    officialUrl: "https://parivahan.gov.in/",
    keywords: [
      "driving licence", "license", "rc", "vehicle", "challan", "parivahan",
      "డ్రైవింగ్ లైసెన్స్", "వాహనం",
    ],
    ...NP,
  }),
  entry({
    id: "epfo",
    name: "EPFO — provident fund",
    nameTe: "ఈపీఎఫ్ఓ — భవిష్య నిధి",
    description: "PF balance, claims, UAN and pension under EPS.",
    descriptionTe: "పీఎఫ్ బ్యాలెన్స్, క్లెయిమ్‌లు, యూఏఎన్, పింఛను.",
    category: "pension",
    audience: ["everyone", "seniors"],
    level: "central",
    department: "Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in/",
    keywords: ["epf", "pf", "uan", "provident fund", "pension", "పింఛను"],
    ...NP,
  }),
  entry({
    id: "jeevan-pramaan",
    name: "Jeevan Pramaan — digital life certificate",
    nameTe: "జీవన్ ప్రమాణ్",
    description: "Digital life certificate for pensioners.",
    descriptionTe: "పింఛనుదారుల డిజిటల్ జీవన ధ్రువీకరణ పత్రం.",
    category: "pension",
    audience: ["seniors"],
    level: "central",
    department: "Ministry of Electronics & IT",
    officialUrl: "https://jeevanpramaan.gov.in/",
    keywords: ["life certificate", "pensioner", "jeevan pramaan", "జీవన్ ప్రమాణ్"],
    ...NP,
  }),
  entry({
    id: "cpgrams",
    name: "CPGRAMS — public grievances",
    nameTe: "ప్రజా ఫిర్యాదులు (CPGRAMS)",
    description: "Lodge and track a grievance against any central department.",
    descriptionTe: "ఏ కేంద్ర శాఖపైనైనా ఫిర్యాదు చేసి, స్థితి చూడవచ్చు.",
    category: "legal",
    audience: ["everyone"],
    level: "central",
    department: "Department of Administrative Reforms",
    officialUrl: "https://pgportal.gov.in/",
    keywords: ["grievance", "complaint", "cpgrams", "ఫిర్యాదు"],
    ...NP,
  }),
  entry({
    id: "cybercrime",
    name: "Report cybercrime",
    nameTe: "సైబర్ నేరం ఫిర్యాదు",
    description:
      "Report online fraud, financial fraud and cybercrime. Financial fraud helpline: 1930.",
    descriptionTe:
      "ఆన్‌లైన్ మోసం, ఆర్థిక మోసం, సైబర్ నేరాల ఫిర్యాదు. హెల్ప్‌లైన్: 1930.",
    category: "safety",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Home Affairs",
    officialUrl: "https://cybercrime.gov.in/",
    keywords: ["cyber", "fraud", "scam", "1930", "మోసం", "సైబర్"],
    ...NP,
  }),
  entry({
    id: "sanchar-saathi",
    name: "Sanchar Saathi — mobile safety",
    nameTe: "సంచార్ సాథి",
    description:
      "Block a lost or stolen phone, and see which connections are in your name.",
    descriptionTe:
      "పోయిన లేదా దొంగిలించబడిన ఫోన్‌ను బ్లాక్ చేయండి; మీ పేరుపై ఉన్న కనెక్షన్లు చూడండి.",
    category: "telecom",
    audience: ["everyone"],
    level: "central",
    department: "Department of Telecommunications",
    officialUrl: "https://sancharsaathi.gov.in/",
    keywords: ["lost phone", "imei", "stolen mobile", "sim", "ఫోన్"],
    ...NP,
  }),
  entry({
    id: "indiapost",
    name: "India Post",
    nameTe: "ఇండియా పోస్ట్",
    description:
      "Post office services, Speed Post tracking, savings schemes, PPF and Sukanya Samriddhi.",
    descriptionTe:
      "పోస్టాఫీసు సేవలు, స్పీడ్ పోస్ట్ ట్రాకింగ్, పొదుపు పథకాలు, పీపీఎఫ్, సుకన్య సమృద్ధి.",
    category: "post",
    audience: ["everyone"],
    level: "central",
    department: "Department of Posts",
    officialUrl: "https://www.indiapost.gov.in/",
    keywords: ["post office", "speed post", "ppf", "sukanya", "పోస్ట్"],
    ...NP,
  }),
  entry({
    id: "ayushman",
    name: "Ayushman Bharat PM-JAY",
    nameTe: "ఆయుష్మాన్ భారత్",
    description: "Health cover scheme — eligibility check and hospital list.",
    descriptionTe: "ఆరోగ్య బీమా పథకం — అర్హత తనిఖీ, ఆసుపత్రుల జాబితా.",
    category: "health",
    audience: ["everyone"],
    level: "central",
    department: "National Health Authority",
    officialUrl: "https://pmjay.gov.in/",
    keywords: ["ayushman", "pmjay", "health card", "ఆరోగ్యం"],
    source: "National Health Authority — PM-JAY",
    sourceUrl: "https://nha.gov.in/PM-JAY",
    lastVerified: V,
  }),
  entry({
    id: "esanjeevani",
    name: "eSanjeevani — free teleconsultation",
    nameTe: "ఈ-సంజీవని",
    description: "Free online doctor consultation run by the health ministry.",
    descriptionTe: "ఆరోగ్య శాఖ నిర్వహించే ఉచిత ఆన్‌లైన్ వైద్య సలహా.",
    category: "health",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Health & Family Welfare",
    officialUrl: "https://esanjeevani.mohfw.gov.in/",
    keywords: ["doctor", "teleconsultation", "వైద్యం"],
    ...NP,
  }),
  entry({
    id: "imd",
    name: "India Meteorological Department",
    nameTe: "భారత వాతావరణ శాఖ",
    description: "Official forecasts, warnings and district bulletins.",
    descriptionTe: "అధికారిక వాతావరణ సూచనలు, హెచ్చరికలు మరియు జిల్లా బులెటిన్లు.",
    category: "farmers",
    audience: ["everyone", "farmers"],
    level: "central",
    department: "Ministry of Earth Sciences",
    officialUrl: "https://mausam.imd.gov.in/",
    keywords: ["weather", "rain", "forecast", "imd", "వాతావరణం", "వర్షం"],
    ...NP,
  }),
  entry({
    id: "ecourts",
    name: "eCourts — case status",
    nameTe: "ఈ-కోర్టులు",
    description: "Case status, cause lists and orders from district courts.",
    category: "legal",
    audience: ["everyone"],
    level: "central",
    department: "Department of Justice",
    officialUrl: "https://ecourts.gov.in/",
    keywords: ["court", "case status", "కోర్టు"],
    ...NP,
  }),
  entry({
    id: "nalsa",
    name: "Free legal aid (NALSA)",
    nameTe: "ఉచిత న్యాయ సహాయం",
    description: "Free legal services for those entitled to them under law.",
    category: "legal",
    audience: ["everyone", "women", "seniors"],
    level: "central",
    department: "National Legal Services Authority",
    officialUrl: "https://nalsa.gov.in/",
    keywords: ["legal aid", "lawyer", "free legal", "న్యాయ సహాయం"],
    ...NP,
  }),
  entry({
    id: "consumer-helpline",
    name: "National Consumer Helpline",
    nameTe: "జాతీయ వినియోగదారుల హెల్ప్‌లైన్",
    description: "Complain about a product, service or seller. Helpline 1915, 8am–8pm.",
    category: "legal",
    audience: ["everyone"],
    level: "central",
    department: "Department of Consumer Affairs",
    officialUrl: "https://consumerhelpline.gov.in/",
    keywords: ["consumer", "complaint", "refund", "వినియోగదారు"],
    ...NP,
  }),
  entry({
    id: "rti",
    name: "RTI Online",
    nameTe: "సమాచార హక్కు (RTI)",
    description: "File a Right to Information request with a central body.",
    category: "legal",
    audience: ["everyone"],
    level: "central",
    department: "Department of Personnel & Training",
    officialUrl: "https://rtionline.gov.in/",
    keywords: ["rti", "information", "సమాచార హక్కు"],
    ...NP,
  }),
  entry({
    id: "pmay",
    name: "PMAY (Urban) — housing scheme",
    nameTe: "పీఎం ఆవాస్ యోజన (పట్టణ)",
    description:
      "The urban housing mission. For rural housing, apply through the Grama Sachivalayam — the rural portal is not linked here because its address could not be confirmed against an official source.",
    descriptionTe:
      "ఇది పట్టణ గృహ పథకం. గ్రామీణ గృహాల కోసం గ్రామ సచివాలయంలో దరఖాస్తు చేసుకోండి.",
    category: "housing",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Housing & Urban Affairs",
    officialUrl: "https://pmaymis.gov.in/",
    keywords: ["housing", "pmay", "ఇల్లు", "గృహ"],
    ...NP,
  }),
  entry({
    id: "udyam",
    name: "Udyam — MSME registration",
    nameTe: "ఉద్యం నమోదు",
    description: "Free MSME registration for a small business.",
    category: "business",
    audience: ["business"],
    level: "central",
    department: "Ministry of MSME",
    officialUrl: "https://udyamregistration.gov.in/",
    keywords: ["msme", "udyam", "business", "వ్యాపారం"],
    ...NP,
  }),
  entry({
    id: "gst",
    name: "GST portal",
    nameTe: "జీఎస్‌టీ పోర్టల్",
    description: "GST registration, returns and payment.",
    category: "business",
    audience: ["business"],
    level: "central",
    department: "Goods and Services Tax Network",
    officialUrl: "https://www.gst.gov.in/",
    keywords: ["gst", "tax", "జీఎస్‌టీ"],
    ...NP,
  }),
  entry({
    id: "nrega-central",
    name: "MGNREGA",
    nameTe: "ఉపాధి హామీ పథకం",
    description: "Job cards, muster rolls and payments under the rural employment guarantee.",
    descriptionTe: "జాబ్ కార్డులు, మస్టర్ రోల్స్, చెల్లింపులు.",
    category: "welfare",
    audience: ["everyone"],
    level: "central",
    department: "Ministry of Rural Development",
    officialUrl: "https://nrega.nic.in/",
    keywords: ["nrega", "mgnrega", "job card", "ఉపాధి హామీ", "కూలి"],
    ...NP,
  }),
];
