/**
 * Student and education services.
 *
 * Only official and openly-licensed sources. Nothing here is a coaching
 * business, and nothing is described as free unless the operating body
 * publishes it free.
 */
import { entry, type DirectoryEntry } from "./types";

const V = "2026-08-28";
const NP = {
  source: "National Portal of India",
  sourceUrl: "https://www.india.gov.in/",
  lastVerified: V,
};

export const STUDENTS: DirectoryEntry[] = [
  entry({
    id: "nsp",
    name: "National Scholarship Portal",
    nameTe: "జాతీయ స్కాలర్‌షిప్ పోర్టల్",
    description: "Central scholarships — application, renewal and status.",
    descriptionTe: "కేంద్ర స్కాలర్‌షిప్‌లు — దరఖాస్తు, పునరుద్ధరణ, స్థితి.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "Ministry of Electronics & IT",
    officialUrl: "https://scholarships.gov.in/",
    keywords: ["scholarship", "nsp", "స్కాలర్‌షిప్", "ఉపకార వేతనం"],
    ...NP,
  }),
  entry({
    id: "apaar",
    name: "APAAR — student ID",
    nameTe: "అపార్ విద్యార్థి ఐడీ",
    description: "One permanent academic ID linking a student's records.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "Ministry of Education",
    officialUrl: "https://apaar.education.gov.in/",
    keywords: ["apaar", "student id", "abc"],
    ...NP,
  }),
  entry({
    id: "swayam",
    name: "SWAYAM — free online courses",
    nameTe: "స్వయం — ఉచిత ఆన్‌లైన్ కోర్సులు",
    description:
      "Free courses from Indian universities, school level to postgraduate. Certification is optional and charged separately.",
    descriptionTe:
      "భారతీయ విశ్వవిద్యాలయాల ఉచిత కోర్సులు. సర్టిఫికెట్ ఐచ్ఛికం, దానికి ఫీజు ఉంటుంది.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "Ministry of Education",
    officialUrl: "https://swayam.gov.in/",
    keywords: ["swayam", "course", "online course", "free course", "కోర్సు"],
    ...NP,
  }),
  entry({
    id: "nptel",
    name: "NPTEL — engineering lectures",
    nameTe: "ఎన్‌పీటెల్",
    description:
      "Free engineering and science lectures from the IITs and IISc.",
    descriptionTe: "ఐఐటీ, ఐఐఎస్‌సీ నుండి ఉచిత ఇంజినీరింగ్, సైన్స్ పాఠాలు.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "IITs and IISc, Ministry of Education",
    officialUrl: "https://nptel.ac.in/",
    keywords: ["nptel", "engineering", "iit", "cse", "ఇంజినీరింగ్"],
    ...NP,
  }),
  entry({
    id: "ndl",
    name: "National Digital Library",
    nameTe: "జాతీయ డిజిటల్ లైబ్రరీ",
    description: "Millions of free books, papers and learning materials.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "Ministry of Education / IIT Kharagpur",
    officialUrl: "https://ndl.iitkgp.ac.in/",
    keywords: ["library", "books", "ndl", "పుస్తకాలు"],
    ...NP,
  }),
  entry({
    id: "nta",
    name: "NTA — national entrance exams",
    nameTe: "ఎన్‌టీఏ — ప్రవేశ పరీక్షలు",
    description: "JEE, NEET, CUET and other national entrance examinations.",
    descriptionTe: "జేఈఈ, నీట్, సీయూఈటీ మొదలైన జాతీయ ప్రవేశ పరీక్షలు.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "National Testing Agency",
    officialUrl: "https://www.nta.ac.in/",
    keywords: ["nta", "jee", "neet", "cuet", "entrance exam", "ప్రవేశ పరీక్ష"],
    ...NP,
  }),
  entry({
    id: "ugc",
    name: "UGC",
    nameTe: "యూజీసీ",
    description: "University Grants Commission — recognised universities and regulations.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "University Grants Commission",
    officialUrl: "https://www.ugc.gov.in/",
    keywords: ["ugc", "university", "degree"],
    ...NP,
  }),
  entry({
    id: "aicte",
    name: "AICTE",
    nameTe: "ఏఐసీటీఈ",
    description: "Technical education regulator — approved institutions and schemes.",
    category: "students",
    audience: ["students"],
    level: "central",
    department: "All India Council for Technical Education",
    officialUrl: "https://www.aicte-india.org/",
    keywords: ["aicte", "engineering college", "technical"],
    ...NP,
  }),
  entry({
    id: "ncert",
    name: "NCERT textbooks",
    nameTe: "ఎన్‌సీఈఆర్‌టీ పాఠ్యపుస్తకాలు",
    description: "Free school textbooks, class 1 to 12.",
    descriptionTe: "1 నుండి 12 తరగతి వరకు ఉచిత పాఠ్యపుస్తకాలు.",
    category: "students",
    audience: ["students", "children"],
    level: "central",
    department: "NCERT, Ministry of Education",
    officialUrl: "https://ncert.nic.in/",
    keywords: ["ncert", "textbook", "school", "పాఠ్యపుస్తకం"],
    ...NP,
  }),
  entry({
    id: "epathshala",
    name: "e-Pathshala",
    nameTe: "ఈ-పాఠశాల",
    description: "NCERT textbooks and learning material as an app and website.",
    category: "students",
    audience: ["students", "children"],
    level: "central",
    department: "NCERT, Ministry of Education",
    officialUrl: "https://epathshala.nic.in/",
    keywords: ["epathshala", "school books"],
    ...NP,
  }),
  entry({
    id: "skillindia",
    name: "Skill India Digital",
    nameTe: "స్కిల్ ఇండియా",
    description: "Government skill courses, apprenticeships and job links.",
    descriptionTe: "ప్రభుత్వ నైపుణ్య కోర్సులు, అప్రెంటిస్‌షిప్‌లు, ఉద్యోగ లింకులు.",
    category: "jobs",
    audience: ["students", "jobseekers"],
    level: "central",
    department: "Ministry of Skill Development",
    officialUrl: "https://www.skillindiadigital.gov.in/",
    keywords: ["skill", "training", "apprentice", "నైపుణ్యం"],
    ...NP,
  }),
  entry({
    id: "ncs",
    name: "National Career Service",
    nameTe: "నేషనల్ కెరీర్ సర్వీస్",
    description: "Government job exchange, career counselling and registration.",
    descriptionTe: "ప్రభుత్వ ఉద్యోగ మార్పిడి, కెరీర్ సలహా, నమోదు.",
    category: "jobs",
    audience: ["jobseekers", "students"],
    level: "central",
    department: "Ministry of Labour & Employment",
    officialUrl: "https://www.ncs.gov.in/",
    keywords: ["jobs", "career", "employment", "ఉద్యోగాలు", "ఉద్యోగం"],
    ...NP,
  }),
  entry({
    id: "appsc",
    name: "APPSC — AP Public Service Commission",
    nameTe: "ఏపీపీఎస్సీ",
    description: "State government recruitment notifications and applications.",
    descriptionTe: "రాష్ట్ర ప్రభుత్వ ఉద్యోగ ప్రకటనలు, దరఖాస్తులు.",
    category: "jobs",
    audience: ["jobseekers"],
    level: "state",
    department: "Government of Andhra Pradesh",
    officialUrl: "https://psc.ap.gov.in/",
    keywords: ["appsc", "government job", "ap job", "ప్రభుత్వ ఉద్యోగం"],
    source: "Government of Andhra Pradesh",
    sourceUrl: "https://www.ap.gov.in/",
    lastVerified: V,
  }),
];
